import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import InicioSesion from '@/components/login'
import NavbarB from '@/components/NavbarB'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ height: '100%' }}>
      <body className=  {inter.className}  style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', margin: 0 }}>
      <NavbarB/>

        <main className="bg-[#E1E5F2]"style={{ flex: 1 }}>{children}  
        
        </main>
        <Footer/>
      </body>
    </html>
  )
}
